### ISSUE TITLE
Error:java.lang.IllegalArgumentException: The transformer object (Python class __main__.new_class) is not a supported Transformer

### ISSUE THREAD

**Issue by gzykarajan** [jpmml/sklearn2pmml-plugin#8]
Hi vruusmann，

I created a new class which extends BaseEstimator, TransformerMixin as follow:

```python
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin

class PipTest(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        self.var = 0
        
    def fit(self, x, y):
        self.var = x - y
        return self
    
    def predict(self, x):
        return x - self.var
    
    def transform(self, x):
        return 2*x
    
test_pipeline = PMMLPipeline([
  ('test', PipTest())
])

x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])

test_pipeline.fit(x, y)
test_pipeline.predict(x)

from sklearn2pmml import sklearn2pmml
sklearn2pmml(test_pipeline, 'test_pipeline.pmml', with_repr = True,debug=True)
```
When I ran the code, I met the issue :
```
Failed to convert
java.lang.IllegalArgumentException: The transformer object (Python class __main__.PipTest) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:45)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:103)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:94)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:599)
	at sklearn.TransformerUtil.getHead(TransformerUtil.java:107)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:194)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Unknown Source)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	... 7 more
```
How to solve this problem?
Thank you!

**Comment by vruusmann** [comment]
You have created a custom tranformer in the **Python side**, but you have not yet created a PMML converter for this custom transformer in the **Java side**.

Please see the example given in "Usage" section of the README file, and try to locate:
1. The Python side of class `com.mycompanyAggregator`
2. The Java side of class `com.mycompany.Aggregator`

You're currently missing the second part in your project.

**Comment by vruusmann** [comment]
BTW, you don't need a custom transformer class to perform arithmetic operations.

The business logic of your `PipTest` transformer class can be 100% implemented using the default `sklearn2pmml.preprocessing.ExpressionTransformer` transformer class.
